name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: contract

jobs:
  register-test:
    name: register
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: register

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./... -count=1

  contract-test:
    name: contract
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contract

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./... -count=1